CREATE DATABASE TOMROGERSUDICT;

USE TOMROGERSUDICT;

CREATE TABLE USER
(
	userid INT(2) NOT NULL AUTO_INCREMENT,
	username VARCHAR(30) UNIQUE,
	passwordhash VARCHAR(255),
	bio VARCHAR(255),
	email VARCHAR(255),
	last_login DATETIME,
	userdate DATETIME,
	admin BOOL DEFAULT 0,
CONSTRAINT USER_PRIMARY_KEY PRIMARY KEY (userid),
CONSTRAINT PK_NOT_ZERO CHECK (userid > 0)
);

CREATE TABLE CATEGORIES
(
	category VARCHAR(255) NOT NULL,
	CONSTRAINT CATEGORY_PK PRIMARY KEY (category)
);

INSERT INTO CATEGORIES (category)
VALUES ('People');

INSERT INTO CATEGORIES (category)
VALUES ('Places');

INSERT INTO CATEGORIES (category)
VALUES ('General');

INSERT INTO CATEGORIES (category)
VALUES ('Misc');

INSERT INTO CATEGORIES (category)
VALUES ('Slang');

INSERT INTO CATEGORIES (category)
VALUES ('Swearing');



CREATE TABLE ENTRY
(
	entryid INT(2) NOT NULL AUTO_INCREMENT,
	userid	INT(2) NOT NULL,
	entryname VARCHAR(255) NOT NULL,
	entrycontent VARCHAR(255),
	category VARCHAR(255),
	entrydate DATETIME,
	lastupdated DATETIME,
CONSTRAINT ENTRY_PRIMARY_KEY PRIMARY KEY (entryid),
CONSTRAINT USERS_FOREIGN_KEY FOREIGN KEY (userid) REFERENCES USER(userid)
ON DELETE CASCADE,
CONSTRAINT CATEGORIESFK FOREIGN KEY (category) REFERENCES CATEGORIES(category),
CONSTRAINT PK_NOT_ZERO CHECK(entry > 0)
);

/* This doesn't need to have a int key, it's better if we just do it like this, however, we do need ENTRIES to have a Foreign Key. */

CREATE TABLE ENTRYREPLIES
(
	replyid INT(2) NOT NULL AUTO_INCREMENT,
	userid	INT(2) NOT NULL,
	entryid INT(2) NOT NULL,
	replycontent VARCHAR(255),
	replydate DATETIME,
	lastupdated DATETIME,
CONSTRAINT REPLY_PRIMARY_KEY PRIMARY KEY (replyid),
CONSTRAINT USERFK FOREIGN KEY (userid) REFERENCES USER(userid) ON DELETE CASCADE,
CONSTRAINT ENTRYFK FOREIGN KEY (entryid) REFERENCES ENTRY(entryid) ON DELETE CASCADE,
CONSTRAINT PK_NOT_ZERO Check(reply > 0)
);
