USE TOMROGERSUDICT;
CREATE TRIGGER ENTRYUPDATE AFTER UPDATE ON ENTRY
FOR EACH ROW 
BEGIN 
	UPDATE ENTRY SET lastupdated = NOW();
END;


CREATE TRIGGER REPLYUPDATE AFTER UPDATE ON ENTRYREPLIES
FOR EACH ROW 
BEGIN 
	UPDATE ENTRYREPLIES SET lastupdated = NOW();
END;

CREATE TRIGGER ENTRYINSERT BEFORE INSERT ON ENTRY
FOR EACH ROW 
BEGIN
	SET NEW.entrydate = NOW();
END;


CREATE TRIGGER REPLYINSERT BEFORE INSERT ON ENTRYREPLIES
FOR EACH ROW 
BEGIN
	SET NEW.replydate = NOW();
END;

CREATE TRIGGER USERINSERT BEFORE INSERT ON USER
FOR EACH ROW
BEGIN
	SET NEW.userdate = NOW();
END;



